[server]
port = 8501
enableCORS = false
enableXsrfProtection = false

[theme]
primaryColor = "#8C1D40"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#262730"
font = "sans serif"

[runner]
magicEnabled = true
installDependencies = true 